src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ParticipantRepository::class)
 * @ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(columns={"pseudo"})})
 * @UniqueEntity("pseudo", message="Ce pseudo est déja pris !")
 * @UniqueEntity("mail", message="Ce mail est déja pris !")
 */
class Participant implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="pseudo",type="string", length=180, unique=true)
     * @Assert\NotBlank()
     */
    private $pseudo;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $prenom;

    /**
     * @ORM\Column(name="mail",type="string", length=150, unique=true)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=10,)
     * @Assert\PositiveOrZero(message="Inserez un numéro valide")
     */
    private $telephone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\ManyToMany(targetEntity=Sortie::class, inversedBy="idparticipant")
     */
    private $sortie;

    /**
     * @ORM\OneToMany(targetEntity=Sortie::class, mappedBy="organisateur")
     */
    private $organisateur;

    /**
     * @ORM\ManyToOne(targetEntity=Site::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $Site;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     */
    private $imageFileName;


    public function __construct()
    {
        $this->sortie = new ArrayCollection();
        $this->organisateur = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    /**
     *@Assert\Length(min="8", minMessage="Votre mot de passe doit comporter au moins huit caractères, dont des lettres majuscules et minuscules, un chiffre et un symbole.")
     */
    public function getPlainPassword(): ?string
    {
        return $this->password;
    }


    public function setPlainPassword(string $user): self
    {
        $this->password = $user;

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSortie(): Collection
    {
        return $this->sortie;
    }

    public function addSortie(Sortie $sortie): self
    {
        if (!$this->sortie->contains($sortie)) {
            $this->sortie[] = $sortie;
        }

        return $this;
    }

    public function removeSortie(Sortie $sortie): self
    {
        $this->sortie->removeElement($sortie);

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getOrganisateur(): Collection
    {
        return $this->organisateur;
    }

    public function addOrganisateur(Sortie $organisateur): self
    {
        if (!$this->organisateur->contains($organisateur)) {
            $this->organisateur[] = $organisateur;
            $organisateur->setOrganisateur($this);
        }

        return $this;
    }

    public function removeOrganisateur(Sortie $organisateur): self
    {
        if ($this->organisateur->removeElement($organisateur)) {
            // set the owning side to null (unless already changed)
            if ($organisateur->getOrganisateur() === $this) {
                $organisateur->setOrganisateur(null);
            }
        }

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->Site;
    }

    public function setSite(?Site $Site): self
    {
        $this->Site = $Site;

        return $this;
    }

    public function getImageFileName(): ?string
    {
        return $this->imageFileName;
    }

    public function setImageFileName(?string $imageFileName): self
    {
        $this->imageFileName = $imageFileName;

        return $this;
    }



















}

src/Controller/ParticipantController.php
<?php

namespace App\Controller;

use App\Entity\Participant;
use App\Entity\Site;
use App\Form\ParticipantType;
use App\Form\RegisterType;
use App\Form\UpdateParticipantType;
use App\Repository\ParticipantRepository;
use App\Security\LoginAuthenticator;
use Doctrine\ORM\EntityManagerInterface;
use http\Client\Curl\User;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @Route (name="participant_", path="participant/")
 */
class ParticipantController extends AbstractController
{
    /**
     * @Route(path="inscription", name="inscription", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN", statusCode=404, message="L'accès est réservé au administrateur")
     */
    public function inscription(EntityManagerInterface $entityManager,
                                Request $request,
                                UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $participant = new Participant();
        $form = $this->createForm(ParticipantType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $admin = $form->get('admin')->getData();
            $imageFile = $form->get('imageUser')->getData();
            if ($admin==true)
                $participant->setRoles(['ROLE_ADMIN']);
            else
                $participant->setRoles(['ROLE_USER']);


            //Tentative d'ajout d'une photo de profil
            if($imageFile) {
                $originalFileName = pathinfo($imageFile->getClientOriginalName(),PATHINFO_FILENAME);
                $safeFileName = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove;'
                .'Lower()', $originalFileName);
                $newFileName = $safeFileName.'-'.uniqid().'.'.$imageFile->guessExtension();

                try {
                    $imageFile->move (
                        $this -> getParameter('images_directory'),
                        $newFileName
                    );
                } catch (FileException $e) {

                }
                $participant -> setImageFileName($newFileName);
            }
            $participant->setPassword($passwordEncoder->encodePassword($participant, $participant->getPlainPassword()));
            $entityManager->persist($participant);
            $entityManager->flush();

            $this->addFlash('success', 'L\'inscritpion a été un succès ! ;)');


           return $this->redirectToRoute('participant_inscription');

        }
        return $this->render('participant/register.html.twig',
            ['participantForm' => $form->createView()]
        );
    }

    /**
     * @Route(path="profil", name="profil")
     * @IsGranted("ROLE_USER", statusCode=404, message="L'accès est réservé au personne inscrite")
     */
    public function profil()
    {
            return $this->render('participant/profil.html.twig', [
                'Controller_name' => 'ParticipantController'
            ]);
    }

    /**
     * @Route(path="profil/update", name="update")
     * @param Request $request
     * @param EntityManagerInterface $emi
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return RedirectResponse|Response
     * @IsGranted("ROLE_USER", statusCode=404, message="L'accès est réservé au personne inscrite")
     */

    public function update(Request $request, EntityManagerInterface $emi,
                           UserPasswordEncoderInterface $passwordEncoder,
                            ValidatorInterface $validator)
    {
        $user = $this->getUser();
        $formUser = $this->createForm(UpdateParticipantType::class, $user);
        $formUser->handleRequest($request);
        $oldImage = $user -> getImageFileName();
        $filename =  $this -> getParameter('images_directory').'/'.$oldImage;
        //dd($filename,$oldImage);


        if ($formUser->isSubmitted() && $formUser->isValid()) {
            if ($formUser->get('passwordPlain')->getData() !== null) {
                $hashed = $passwordEncoder->encodePassword($user, $formUser->get('passwordPlain')->getData());
                $user->setPassword($hashed);
            }
                $newImage = $formUser->get('imageUser')->getData();
                //dd($filename,$oldImage);
                //Tentative de remplacement de la photo de profil
                if($newImage) {
                    $originalFileName = pathinfo($newImage->getClientOriginalName(),PATHINFO_FILENAME);
                    $safeFileName = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove;'
                        .'Lower()', $originalFileName);
                    $newFileName = $safeFileName.'-'.uniqid().'.'.$newImage->guessExtension();

                    try {
                        $newImage->move (
                            $this -> getParameter('images_directory'),
                            $newFileName
                        );
                    } catch (FileException $e) {

                    }
                    $user -> setImageFileName($newFileName);

                    if (!empty($oldImage) && file_exists($filename)) {
                        unlink($filename);
                    }
                }

                $error = false;

                $pseudo = $formUser->get('pseudoPlain')->getData();
                if(strcmp($pseudo, $user->getPseudo()) != 0 ){
                    //pseudo différent
                    $pTest = new Participant();
                    $pTest->setPseudo($pseudo);
                    $errors = $validator->validate($pTest);

                    if(count($errors) == 0){
                        $user->setPseudo($pseudo);
                    }
                    else{
                        $error = true;
                        $formUser->get('pseudoPlain')->addError(new FormError($errors[0]->getMessage()));
                    }

                }

                if(!$error) {
                    $emi->persist($user);
                    $emi->flush();

                    /*
                     $user->setImageFileName(
                         new File($this->getParameter('images_directory').'/'.$user->getImageFileName())
                     );
                    */
                    return $this->redirectToRoute("participant_profil", ["id" => $user->getId()]);
                }
            }

        return $this->render("participant/update.html.twig", [
            'formUser' => $formUser->createView(),
            'user' => $user
        ]);
    }
    /**
     * @Route(path="profilParticipant/{id}", name="profilParticipant", methods={"GET","Post"}, requirements={"id": "\d+"})
     * @IsGranted("ROLE_USER", statusCode=404, message="L'accès est réservé au personne inscrite")
     */
    public function profilParticipant($id, ParticipantRepository $repository)
    {
        $p = $repository->find($id);
        return $this->render('participant/profilParticipant.html.twig', [
            'p'=>$p,
            'Controller_name' => 'ParticipantController'
        ]);
    }
}

templates/participant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ParticipantController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">


    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Administrateur/Symfony Project/sortir.com/src/Controller/ParticipantController.php'|file_link(0) }}">src/Controller/ParticipantController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Administrateur/Symfony Project/sortir.com/templates/participant/sortie.html.twig'|file_link(0) }}">templates/participant/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/participant/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bonjour,{{ app.user.nom}} {% endblock %}

{% block body %}
    <div class="container d-flex justify-content-center ">
        <div class="card p-4 mt-2 ">
            <div class="first">
                <h1 class="heading">{{ app.user.nom }} {{ app.user.prenom }}</h1>
                <div class="time d-flex flex-row align-items-center justify-content-between mt-3">
                    <div class="d-flex align-items-center"><span class="hour ml-1">Pseudo : {{ app.user.pseudo }}</span> </div>
                </div>
            </div>
            <div class="second d-flex flex-row mt-2">
                {% if app.user.imageFileName is not null %}
                    <div class="image mr-3"> <img src="{{ asset('build/uploads/imageUser/' ~ app.user.imageFileName) }}" width="150rem" height="150rem" class="rounded-circle img-thumbnail"></div>

                {% else %}
                    <img src="{{ asset ('build/images/Avatar-default.png') }}" width="150rem" height="150rem"
                         class="rounded-circle img-thumbnail">
                {% endif %}
                <div class="">
                    {% if app.user.mail is not null %}
                        Mail :
                        <a href="#" class="d-block"> {{ app.user.mail }}</a>
                    {% endif %}
                    {% if app.user.telephone is not null %}
                        Numéro de Téléphone :
                        <a href="#" class="d-block"> {{ app.user.telephone }}</a>
                    {% endif %}
                        Campus :
                    <a href="#" class="d-block"> {{ app.user.site.nom}} </a>
                </div>
            </div>
            <hr class="line-color">
            {% if app.user.id is not null %}
            <div class="third mt-4"> <a class="btn btn-info btn-block" href="{{ url('participant_update') }}"> Modifier profil</a>
            </div>
            {% endif %}

        </div>
    </div>
    </div>
{% endblock %}

templates/participant/profilParticipant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bonjour,{{ p.nom}} {% endblock %}

{% block body %}
    <div class="container d-flex justify-content-center ">
    <div class="card p-4 mt-2 ">
        <div class="first">
            <h1 class="heading">{{ p.nom }} {{ p.prenom }}</h1>
            <div class="time d-flex flex-row align-items-center justify-content-between mt-3">
                <div class="d-flex align-items-center"><span class="hour ml-1">Pseudo : {{ p.pseudo }}</span>
                </div>
            </div>
        </div>
        <div class="second d-flex flex-row mt-2">
            {% if p.imageFileName is not null %}
                <div class="image mr-3"> <img src="{{ asset('build/uploads/imageUser/' ~ p.imageFileName) }}" width="150rem" height="150rem" class="rounded-circle img-thumbnail"></div>
            {% else %}
                <img src="{{ asset ('build/images/Avatar-default.png') }}" width="150rem" height="150rem"
                     class="rounded-circle img-thumbnail">
            {% endif %}
            <div class="">
                {% if p.mail is not null %}
                    Mail :
                    <a href="#" class="d-block"> {{ p.mail }}</a>
                {% endif %}
                {% if p.telephone is not null %}
                    Numéro de Téléphone :
                    <a href="#" class="d-block"> {{ p.telephone }}</a>
                {% endif %}
                Campus :
                <a href="#" class="d-block"> {{ p.site.nom }} </a>
            </div>
        </div>
        <hr class="line-color">
    </div>
    </div>
{% endblock %}

templates/participant/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription d'un nouvel utilisateur{% endblock %}

{% block body %}



    <h1>Inscription d'un nouvel utilisateur</h1>

    {# read and display all flash messages #}
    {% for type, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ type }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    {{ form_start(participantForm) }}
    <div class="border-lg mb-5 box-shadow rounded">
        <div class="container border-bottom box-shadow">
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form_label((participantForm.pseudo)) }}
                        {{ form_widget(participantForm.pseudo, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label((participantForm.admin)) }}
                        {{ form_widget(participantForm.admin, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label((participantForm.plainPassword)) }}
                        {{ form_widget(participantForm.plainPassword, {'attr': {'class': 'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label((participantForm.nom)) }}
                        {{ form_widget(participantForm.nom, {'attr': {'class': 'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label((participantForm.prenom)) }}
                        {{ form_widget(participantForm.prenom, {'attr': {'class': 'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label((participantForm.telephone)) }}
                        {{ form_widget(participantForm.telephone, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form_label((participantForm.mail)) }}
                        {{ form_widget(participantForm.mail, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label((participantForm.actif)) }}
                        {{ form_widget(participantForm.actif, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label((participantForm.site)) }}
                        {{ form_widget(participantForm.site, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label((participantForm.imageUser)) }}
                        {{ form_widget(participantForm.imageUser, {'attr': {'class': 'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_widget(participantForm.submit, {'attr': {'class': 'btn btn-primary'}}) }}
                    </div>
                </div>
            </div>

        </div>
    </div>

    {{ form_end(participantForm) }}

{% endblock %}

templates/participant/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Profil{% endblock %}

{% block body %}

    {% form_theme formUser 'bootstrap_4_layout.html.twig' %}


    <div class="row">
        <div class="col">
            <h2>Mon profil</h2>
            <hr>
        </div>
    </div>

    {{ form_start(formUser) }}
    <div class="border-lg mb-5 box-shadow rounded">
        <div class="container border-bottom box-shadow">
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form_row(formUser.pseudoPlain) }}
                    </div>

                    <div class="form-group">
                        {{ form_row(formUser.nom) }}
                    </div>

                    <div class="form-group">
                        {{ form_row(formUser.prenom) }}
                    </div>

                    <div class="form-group">
                        {{ form_row(formUser.mail) }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form_row(formUser.telephone) }}
                    </div>

                    <div class="form-group">
                        {{ form_row(formUser.passwordPlain) }}
                    </div>
                    <div class="form-group">
                        {{ form_label((formUser.imageUser)) }}
                        {{ form_widget(formUser.imageUser, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
            </div>
            <div class="d-flex align-items justify-content-center">
                <div class="form-group mr-4">
                    <button class="btn btn-info mt-4" type="submit">Confirmer</button>
                </div>
                <div class="form-group">
                    <a class="btn btn-outline-danger mt-4" href="{{ path('participant_profil') }}">Annuler</a>
                </div>
            </div>
        </div>
    </div>

    {{ form_end(formUser) }}


{% endblock %}